### ISSUE TITLE
Change table.unpack to unpack in number.lua?

### ISSUE THREAD

**Issue by oemsysadm** [thenumbernine/lua-ext#4]
Hi, I'm trying to use bignumber (and ext because of this) with love2d, and am running into an issue where ext/number.lua generates an error. I'm no lua programmer, but it seems "table.unpack" perhaps has been deprecated in favor of simply "unpack"?

Indeed changing this in number.lua appears to fix the issue.

I'm a little hazy on if this is will be an issue with other lua implementations, but thought I should open an issue with you because of this.

**Comment by thenumbernine** [comment]
I think you've got that backwards.  unpack was deprecated in favor of table.unpack:
```
$ROOT/lua/ext$ lua5.4
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
> table.unpack
function: 0x564e1607a960
> unpack
nil

$ROOT/lua/ext$ lua5.3
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> table.unpack
function: 0x56424df5aeb0
> unpack
nil

$ROOT/lua/ext$ lua5.2
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> =table.unpack
function: 0x55b469a9faa0
> =unpack
function: 0x55b469a9faa0

$ROOT/lua/ext$ lua5.1
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> =table.unpack
nil
> =unpack
function: 0x559395f04870
```

**Comment by oemsysadm** [comment]
So love2d just didn't catch up :) Sorry!

**Comment by thenumbernine** [comment]
No worries, you have me thinking how to make sure this is 5.1 compatible.  It was supposed to be after all, hence why ext.table defines table.unpack if it's not already defined.  and why os.execute wraps the return-value for older Lua versions with returning true/false and a message first (to be assert-compat) rather than the old API of just returning the system error code.

**Comment by thenumbernine** [comment]
Here's the bug that you discovered:
```
$ lua5.1 -e "require 'ext.number'.charfor(10)"
lua5.1: /home/chris/Projects/lua/ext/number.lua:30: attempt to call field 'unpack' (a nil value)
stack traceback:
	/home/chris/Projects/lua/ext/number.lua:30: in function 'charfor'
	(command line):1: in main chunk
	[C]: ?
```

**Comment by thenumbernine** [comment]
ok should be fixed now:
```
$ lua5.1 -e "print(require 'ext.number'.charfor(10))"
a
```
